### ISSUE TITLE
March Node Breakfast - Date Proposal

### ISSUE THREAD

**Issue by totherik** [BayNode/nodebreakfast#1]
Hey guys, I 'm scheduled for jury duty the week of the 17th, so I want to propose the week of March 10 for Node Breakfast, hosted here at PayPal.

[Let me know what date works best](https://www.surveymonkey.com/s/D8RT8VY) and if this week is bad for everyone, we'll move it.

**Where:** [2211 N 1st St, San Jose, California 95131](https://goo.gl/maps/x5qTv)

**When:** 9 - 10:30am, Thursday, March 20, 2014

**Who:**
- [x] Adam Crabtree (LinkedIn)
- [x] Ross Kukulinski (Advanced Simulation Technology Inc.)
- [x] Daniel Shaw (The Node Firm)
- [x] Erik Toth (PayPal)
- [ ] Dav Glass, Reid Burke (Yahoo)
- [x] Fred K. Schott, Nicholas Zakas (Box)
- [ ] Jacob Chapel (Walmart)
- [x] Alex Liu (Netflix)
- [ ] Trevor Norris (Mozilla)
- [x] Tony Pujals (Hacker Dojo)

**Comment by rosskukulinski** [comment]
Filled out your survey for the 13th, but 10th or 14th also work.  Thanks for organizing!

**Comment by totherik** [comment]
Thanks @rosskukulinski! I fixed the survey to allow multiple dates and updated your response to reflect those, FYI

**Comment by totherik** [comment]
Ok, guys, Friday, March 14?

**Comment by FredKSchott** [comment]
:+1:

**Comment by CrabDude** [comment]
[image: :+1:]

**Comment by subfuzion** [comment]
+1

**Comment by rosskukulinski** [comment]
+1 works for me

**Comment by dshaw** [comment]
No can do for both @trevnorris and I on the 14th. Performance analysis time: http://firm.io/perf-beta

**Comment by totherik** [comment]
I'm cool with pushing out to the 20th or 21st. Just may have to convince someone on my team to host...

**Comment by dshaw** [comment]
:+1:  for Thursday 3/20

**Comment by rosskukulinski** [comment]
I could do 20th or 21st.

**Comment by CrabDude** [comment]
Yes

**Comment by totherik** [comment]
Ok, settled. Switching to Thursday 3/20. Your lovely host will be @jeffharrell that day. :grinning:

**Comment by jeffharrell** [comment]
"lovely" - ha.

And I'm following this now to get updates rather than bugging Erik :smile:

**Comment by reid** [comment]
Sadly can't make it, I'm out of town 3/18-3/25. Will be subscribing to this repo for future date proposals!

**Comment by FredKSchott** [comment]
Still on for tomorrow? Looking forward to some node and coffee :yum:

**Comment by CrabDude** [comment]
What time?

**Comment by totherik** [comment]
Still on. 9 in the am.

**Comment by CrabDude** [comment]
Sorry, forgot this was a github issue. Email chain doesn't time for some
reason.

**Comment by rosskukulinski** [comment]
Anything special to get signed in? Find the room?

**Comment by totherik** [comment]
@jeffharrell will meet you guys at the front desk in the main lobby.

**Comment by DonutEspresso** [comment]
I'm running a bit late - be there around 9:10.

**Comment by FredKSchott** [comment]
Hey guys, I greatly underestimated how long the light rail would take from MTV.  The train won't get there until ~10, so I think I'll have to skip it this time. Sorry about that, wish I could be there!

**Comment by totherik** [comment]
Gah, that sucks man. I couldn't make it either, and I KNOW the one time we're not there it's probably the BEST NODE BREAKFAST EVAR! lol.

**Comment by rosskukulinski** [comment]
@totherik wow did you and @FredKSchott miss out :)

Thanks @jeffharrell for hosting!

**Comment by FredKSchott** [comment]
![i'm literally crying right now](http://replygif.net/i/347.gif)

We'll have to make the next one just as good to make up for it :)

**Comment by subfuzion** [comment]
Hey guys -- I had every intention of going, but didn't realize I had a
conflict until last minute. I just started a new job at Appcelerator. The
company's all in on the Node bandwagon and will be building out a new
middleware stack for its Mobile-Backend-as-a-Service platform. I'm pretty
jazzed to be here. I'll definitely catch up with you guys at the next
breakfast -- and ideally a bunch of you will also come to beer.node happy
hour at Steins (March 27, 6pm)! Cheers!

Tony

**Comment by subfuzion** [comment]
Adam scheduled Beer.node for next Thursday and this is going to be a
recurring event. Here are the details. Should be fun!

http://www.meetup.com/BayNode/events/170937102/

**Comment by aheckmann** [comment]
Had a great time yesterday. Thanks for the invite @dshaw!
