### ISSUE TITLE
April Node Breakfast

### ISSUE THREAD

**Issue by subfuzion** [BayNode/nodebreakfast#2]
Hey guys -- I'd love to propose ~~Wednesday, April 30~~ **Friday, May 16** for our next Node Breakfast, hosted at my new employer, Appcelerator in Mountain View.

**Where:** [440 N. Bernardo Avenue Mountain View, CA, 94043](http://goo.gl/115qnP)

**When:** 9 - 10:30 am Friday, May 16,  2014

**Who:**
- [ ] Adam Crabtree (LinkedIn)
- [ ] Ross Kukulinski (Advanced Simulation Technology Inc.)
- [x] Daniel Shaw (The Node Firm)
- [x] Erik Toth (PayPal)
- [x] Dav Glass, Reid Burke (Yahoo)
- [x] Fred K. Schott, Nicholas Zakas (Box)
- [x] Jacob Chapel (Walmart)
- [ ] Alex Liu (Netflix)
- [x] Trevor Norris (Mozilla)
- [x] Tony Pujals (Appcelerator)

Please edit the name list if I missed anybody, and add a comment if you want to propose an alternate date. Any date will work for me.

**Comment by dshaw** [comment]
Dates are mismatched. s/March/April.

**Comment by jeffharrell** [comment]
I'm out for anything April/May.

**Comment by subfuzion** [comment]
Thanks for the catch, @dshaw.

**Comment by rosskukulinski** [comment]
works for me, thanks for the offer to host.

**Comment by subfuzion** [comment]
It's probably too short of notice for many of you at this point. I'm going to move it out another 3 weeks to May 14. Feel free to comment and propose alternate dates that might work best.

**Comment by reid** [comment]
May 14 works for me.

**Comment by rosskukulinski** [comment]
I'll be in DC that week, but no need to hold out for me... I can catch the next one.

**Comment by CrabDude** [comment]
I'll be giving a bootcamp that week. I could do May 16 though.

**Comment by FredKSchott** [comment]
It's been too long! I can do any day that week

**Comment by subfuzion** [comment]
If I switch the date to May 16, how does that work for everyone else? Feel free to post alternative dates...

**Comment by FredKSchott** [comment]
16th works for me

**Comment by CrabDude** [comment]
👍

**Comment by reid** [comment]
The 16th works for me, too.

**Comment by subfuzion** [comment]
Awesome! Hoping to get a few more RSVPs still...

**Comment by dshaw** [comment]
I should be able to make it this Friday. :+1:

**Comment by subfuzion** [comment]
Looking forward to Friday morning. :+1: 

Anyone else able to make it (Erik, Jacob, Alex, Trevor)?

**Comment by totherik** [comment]
Yeah, I think I can make it. See you guys friday.

**Comment by chapel** [comment]
I should be able to make it. Have a meeting at 10am though, so I will be leaving about 10 minutes before that.

**Comment by subfuzion** [comment]
Awesome!

**Comment by dshaw** [comment]
++@trevnorris too. See you all tomorrow.

**Comment by subfuzion** [comment]
Very cool, looking forward to it.

**Comment by CrabDude** [comment]
Hey guys,

I'm really sorry, but I'm not going to be able to make it out this morning.
There's something I have to be at that I forgot about. Next time!

Cheers,
Adam

**Comment by subfuzion** [comment]
Some great discussions (and rants) today along with some great takeaways -- can't believe it went til 11:30. I updated the survey form to reflect who showed. Thanks for coming!

**Comment by FredKSchott** [comment]
+1000 Thanks for hosting Tony!
