### ISSUE TITLE
July Node Breakfast

### ISSUE THREAD

**Issue by subfuzion** [BayNode/nodebreakfast#3]
Hey everyone -- no one proposed a June breakfast, and it's a bit late now, so how about a ~~July~~ **August** breakfast? I'm happy to host again, but I figured someone else might want to have the opportunity next. Please feel free to edit this or to make proposals in the comments.

**Where:** Neflix
100 Winchester Circle,
Los Gatos, CA 95032
[Map](https://www.google.com/maps/place/100+Winchester+Cir,+Los+Gatos,+CA+95032/@37.25959,-121.962646,17z/data=!3m1!4b1!4m2!3m1!1s0x808e3509df82443b:0x89131b6ef914247c)

**When:** 9 - 10:30 AM, Friday, August 8, 2014 (_TBD_)

**Who:**
- [x] Adam Crabtree @CrabDude (Noderiety)
- [x] Alex Liu @balexliu (Netflix)
- [ ] Dav Glass @davglass, Reid Burke @reid (Yahoo)
- [x] Daniel Shaw @dshaw (NodeSource) 
- [x] Erik Toth @totherik, Jeff Harrell @jeffharrell (PayPal)
- [x] Fred K. Schott @FredKSchott , Nicholas Zakas @nzakas (Box)
- [x] Jacob Chapel @chapel (Walmart)
- [x] Ross Kukulinski @rosskukulinski (SpeakIt.io)
- [x] Tony Pujals @tonypujals (Appcelerator)
- [x] Trevor Norris @trevnorris (NodeSource)

**Comment by FredKSchott** [comment]
Tony shouldn't have to host again, Ross mentioned something about Hobees... 😋

I'm pretty busy the next two weeks, but I'd love to do an early August breakfast.

**Comment by subfuzion** [comment]
I actually don't mind hosting and Jeff (CEO) said any time is fine. I think we had a pretty good session here, but I just don't want to hog the venue if others want to host, plus maybe others want to see a rotation around the area that means less driving for them. But in any case, anywhere, including Hobees, sounds good to me.

**Comment by subfuzion** [comment]
I agree with Fred ... I think it's a bit too late in the month at this point for coordination; early August would be good. I put Friday August 8 down as a tentative proposal...

**Comment by dshaw** [comment]
Trevor now works at NodeSource. ;-)

**Comment by DonutEspresso** [comment]
Netflix would be happy to host the next one. Let me work on the logistics, I'll keep everyone posted.

**Comment by CrabDude** [comment]
I'm no longer working on enterprise node, but I do have an idea that's very
enterprise node so I suppose I could join.

**Comment by rosskukulinski** [comment]
Awesome!  Thanks Alex & Netflix!

Ross

**Comment by subfuzion** [comment]
@dshaw @trevnorris that's awesome!  :punch:

@balexliu thanks! :+1:

@CrabDude It's a BayNode event and you're the founder!  :wink:

**Comment by dshaw** [comment]
@balexliu Fantastic.

**Comment by chapel** [comment]
Count me in.

**Comment by trevnorris** [comment]
I can make it. Though switch Mozilla to NodeSource.

**Comment by davglass** [comment]
I'm in town next week, so I won't be in town for this one :crying_cat_face:

**Comment by CrabDude** [comment]
Technically, this isn't related to BayNode in any way. Daniel wanted to
organize an Enterprise node.js  group to share enterprise experience and so
reached out to me because I worked at LinkedIn. Around the same time, you
and Ross came on as BayNode organizers so I invited you both. I think I can
still contribute from the "enterprise" mindset, but I also wanted to
maintain the integrity of the original purpose because I believe it is
important.

**Comment by dshaw** [comment]
@CrabDude I appreciate the concern. Personally, I think you still have something to add. Please feel free to contribute as long as you get something out of it and feel like it's a good use of your time.

I'd like to push the critical mass of this initiative to the next level later this fall. I'll share my thoughts at this meeting.

**Comment by nzakas** [comment]
If I was physically able, I'd totally be there. But alas, I'm not quite up
to public outings at this point. I'll be there in spirit and look forward
to the day when I can be there in person.
​

**Comment by DonutEspresso** [comment]
Hi all, got an update here. We can do the Fridays of the month, except for the second one:

August 8th
August 22nd 
August 29th

Times are flexible, we can stick with the original 9-10:30am slot if that still works for everyone.

**Comment by rosskukulinski** [comment]
Hi @balexliu - all of those dates work for me.  Thanks again for organizing.

**Comment by chapel** [comment]
I don't have anything conflicting that I know of.

**Comment by FredKSchott** [comment]
I'll probably be up in the city for Outside Lands on the 8th, but the other weekends work fine.

**Comment by CrabDude** [comment]
All good for me.

**Comment by dshaw** [comment]
@balexliu Whatever works best for you. I should be able to make all those dates work.

**Comment by DonutEspresso** [comment]
Great, why don't we stick with the 8th then? Let's get something on the calendar sooner than later. I'll send out more info closer to the date about where/how to get in once you arrive that morning.

**Comment by dshaw** [comment]
@balexliu :thumbsup: Sounds great.

**Comment by subfuzion** [comment]
👍

**Comment by DonutEspresso** [comment]
BTW, I would love to invite everyone in this group out to Netflix again later in the month as well. Micah, whom some of you have met, and I will be giving a presentation about the challenges of doing A/B testing at scale on the Netflix website. Some of you (lookin' at you, NodeSource) have been exposed to a bit of this already, but it should be great fun nonetheless. Feel free to bring your heckling props with you. :)

EDIT: Removed event link, as it is invite only for now, will send you guys the event link privately.

**Comment by dshaw** [comment]
:-) Awesome! I will bring the heckling props! :tada:

**Comment by totherik** [comment]
I can't check my name, but I'll be there.

**Comment by jeffharrell** [comment]
I'm tentative, but I think I'll be able to make it.

**Comment by DonutEspresso** [comment]
Is anyone else coming that hasn't said so yet? We'll be ordering some breakfast items, want to make sure we have enough for everyone.

**Comment by reid** [comment]
I'm in.

**Comment by rosskukulinski** [comment]
I'm also tentative, but I think I should be able to make it.  Family in town from France is keeping me on my toes.

**Comment by CrabDude** [comment]
Are we dividing and conquering the workshops? There are too many for me to
have done. Split them up evenly?

**Comment by CrabDude** [comment]
Oops. Wrong BayNode thread. ;)

**Comment by dshaw** [comment]
Also, still in. Looking forward to seeing everybody on Friday!

**Comment by FredKSchott** [comment]
I'll try my best to make it down, but will probably be stuck in the city for the day.

**Comment by subfuzion** [comment]
I'm in. :+1:

**Comment by chapel** [comment]
Do we have an address for this?

**Comment by micahr** [comment]
[100 Winchester Circle,
Los Gatos, CA 95032](https://www.google.com/maps/place/100+Winchester+Cir,+Los+Gatos,+CA+95032/@37.25959,-121.962646,17z/data=!3m1!4b1!4m2!3m1!1s0x808e3509df82443b:0x89131b6ef914247c)

**Comment by DonutEspresso** [comment]
Whoops, forgot to update this! You'll want to go to building A, there is guest parking right outside. When you get to the lobby just ask for me or Micah, we'll come and fetch you guys.

**Comment by reid** [comment]
I can't make it. I hope to see you folks at the next one!
