### ISSUE TITLE
November Breakfast

### ISSUE THREAD

**Issue by DonutEspresso** [BayNode/nodebreakfast#4]
Been awhile since the last breakfast - anybody up for something in November?

**Comment by subfuzion** [comment]
Hey Alex, I was just thinking the same thing.... I'm in!

**Comment by rosskukulinski** [comment]
sounds tasty

**Comment by aheckmann** [comment]
SGTM

**Comment by rosskukulinski** [comment]
ping?  If no corp can host, how about at 

Hobee's
2312 Central Expy
Mountain View, CA

**Comment by FredKSchott** [comment]
Seconded Hobee's and their world-famous blueberry coffeecake :yum:

**Comment by FredKSchott** [comment]
How do people feel about the week before thanksgiving (17th-21st)? Is anyone going away?

**Comment by rosskukulinski** [comment]
I'm in town, early in the week would be better.  I'm hosting an Ansible meetup on the 19th, and BayNode talk night on the 20th.

**Comment by CrabDude** [comment]
I'm always down.

**Comment by totherik** [comment]
yes please. my schedule is wacky for the next few weeks tho, so don't schedule around me.

**Comment by dshaw** [comment]
Wednesday 11/18? That week is pretty bonkers for me, but Wednesday's the most sane.

**Comment by CrabDude** [comment]
I personally can't do next week M-W.

**Comment by DonutEspresso** [comment]
Tue works for me.

**Comment by dshaw** [comment]
Let's Doodle it up: http://doodle.com/idurd7e22ansepds
